### PR TITLE
Update Jenkinsfile for Sonar to use JDK11

### PR DESCRIPTION
**Pull request by shaundmorris**
### Requirements
* Filling out the template is required. Any pull request that does not
include enough information to be reviewed in a timely manner may be
closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change
SonarCloud now requires analysis executing with Java 11. https://sonarcloud.io/documentation/appendices/end-of-support/

### Benefits
SonarCloud analysis will continue to get pushed

### Verification Process
Successful build and analysis on SonarCloud. https://sonarcloud.io/dashboard?id=acdebugger

---
This change is [Reviewable](https://reviewable.io/reviews/codice/acdebugger/60)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Review by TonyMorrison — APPROVED** [review]

**Comment by TonyMorrison** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Pull request closed without merging**
