### PR TITLE
Updated jenkinsfile to report status of pr builds

### LINKED ISSUE #28: Make PR Builds Comment Driven
### Description

Currently pull requests are built when created and when updated. Migrate to using a comment driven approach instead to match other Codice projects

### PR DESCRIPTION
**Pull request by oconnormi**
### Requirements
* Filling out the template is required. Any pull request that does not
include enough information to be reviewed in a timely manner may be
closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change
The pipeline will now register a github check for each of the stages, and will update those with a pass/fail status as the pipeline progresses.

The pipeline will now comment on a pull request when it starts and finishes

### Benefits
Better feedback of build status on pull requests

### Verification Process

Run `Build Now`

### Applicable Issues

Fixes: #28

### CODE REVIEW

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
:crossed_fingers: Build Now

**Review by paouelle — APPROVED** [review]

**Comment by oconnormi** [comment]
testing the last commit, build now

**Pull request merged**
