### PR TITLE
Commented out the windows stages and upgraded dependency-check to 5.2.2

### PR DESCRIPTION
**Pull request by AdamBurstynski**
Windows nodes are no longer available on the build system.

### Description of the Change

Commented out the windows stages in the Jenkinsfile.
Windows nodes are no longer available on the build system.

@shaundmorris 
@TonyMorrison 
@LinkMJB 
@oconnormi 
Can I get a review?

### CODE REVIEW

**Comment by AdamBurstynski** [comment]
build now

**Comment by AdamBurstynski** [comment]
build now

**Comment by AdamBurstynski** [comment]
build now

**Comment by AdamBurstynski** [comment]
build now

**Review by LinkMJB — APPROVED** [review]

**Review by shaundmorris — APPROVED** [review]

**Pull request merged**
